name: deploy-site

# Only run this when the main branch changes
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install packages
      run: |
        npm install

    - name: Build site
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
